// This is an autogenerated file from Firebase Studio.
'use client';

import { useState } from 'react';
import * as pdfjsLib from 'pdfjs-dist';

// Set worker source
if (typeof window !== 'undefined') {
  pdfjsLib.GlobalWorkerOptions.workerSrc = `//unpkg.com/pdfjs-dist@${pdfjsLib.version}/build/pdf.worker.min.mjs`;
}

export function usePdfToText() {
  const [text, setText] = useState<string>('');
  const [isLoading, setIsLoading] = useState<boolean>(false);
  const [error, setError] = useState<string | null>(null);

  const extractText = async (file: File) => {
    setIsLoading(true);
    setError(null);
    setText('');

    try {
      const arrayBuffer = await file.arrayBuffer();
      const pdf = await pdfjsLib.getDocument(arrayBuffer).promise;
      const numPages = pdf.numPages;
      let fullText = '';

      for (let i = 1; i <= numPages; i++) {
        const page = await pdf.getPage(i);
        const textContent = await page.getTextContent();
        const pageText = textContent.items.map((item) => ('str' in item ? item.str : '')).join(' ');
        fullText += pageText + '\n\n';
      }
      
      setText(fullText);
    } catch (err: any) {
      console.error('Error extracting text from PDF:', err);
      setError('Failed to extract text from the PDF. The file might be corrupted or in an unsupported format.');
    } finally {
      setIsLoading(false);
    }
  };

  return { text, isLoading, error, extractText };
}

    