// This is an autogenerated file from Firebase Studio.
'use client';

import { useState, useEffect } from 'react';
import { useRouter } from 'next/navigation';
import { useForm, type UseFormReturn } from 'react-hook-form';
import { zodResolver } from '@hookform/resolvers/zod';
import { z } from 'zod';
import { onAuthStateChanged, signOut, type User } from 'firebase/auth';
import { auth, db } from '@/lib/firebase';
import { Button } from '@/components/ui/button';
import { Textarea } from '@/components/ui/textarea';
import { useToast } from '@/hooks/use-toast';
import { analyzeTos, type AnalysisResult, getConversationHistory, type Conversation } from '@/app/actions';
import { Loader2, LogOut, FileUp, FileText, Bot, User as UserIcon } from 'lucide-react';
import { AnalysisDisplay } from '@/components/app/analysis-display';
import { Header } from '@/components/app/header';
import { Footer } from '@/components/app/footer';
import { Tabs, TabsContent, TabsList, TabsTrigger } from '@/components/ui/tabs';
import { Input } from '@/components/ui/input';
import { usePdfToText } from '@/hooks/use-pdf-to-text';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { Avatar, AvatarFallback, AvatarImage } from '@/components/ui/avatar';
import { ScrollArea } from '@/components/ui/scroll-area';
import { doc, setDoc, serverTimestamp, onSnapshot, collection, query, orderBy } from 'firebase/firestore';


const formSchema = z.object({
  tos: z.string().min(100, {
    message: 'Terms of Service must be at least 100 characters.',
  }),
});

export default function DashboardPage() {
  const [user, setUser] = useState<User | null>(null);
  const [analysis, setAnalysis] = useState<AnalysisResult | null>(null);
  const [isLoading, setIsLoading] = useState(false);
  const [tosContent, setTosContent] = useState('');
  const [analysisId, setAnalysisId] = useState<string | null>(null);
  const [conversationHistory, setConversationHistory] = useState<Conversation[]>([]);
  const router = useRouter();
  const { toast } = useToast();

  useEffect(() => {
    const unsubscribe = onAuthStateChanged(auth, (user) => {
      if (user) {
        setUser(user);
      } else {
        router.push('/login');
      }
    });
    return () => unsubscribe();
  }, [router]);

  useEffect(() => {
    if (user && analysisId) {
      const q = query(collection(db, 'users', user.uid, 'history', analysisId, 'conversations'), orderBy('createdAt', 'asc'));
      const unsubscribe = onSnapshot(q, (querySnapshot) => {
        const history: Conversation[] = [];
        querySnapshot.forEach((doc) => {
          history.push({ id: doc.id, ...doc.data() } as Conversation);
        });
        setConversationHistory(history);
      });
      return () => unsubscribe();
    }
  }, [user, analysisId]);

  const form = useForm<z.infer<typeof formSchema>>({
    resolver: zodResolver(formSchema),
    defaultValues: { tos: '' }
  });

  const handleSignOut = async () => {
    await signOut(auth);
    router.push('/');
  };

  const onSubmit = async (values: z.infer<typeof formSchema>) => {
    if (!user) {
      toast({ variant: 'destructive', title: 'Not authenticated', description: 'You must be logged in to analyze a document.' });
      return;
    }
    setIsLoading(true);
    setAnalysis(null);
    setTosContent(values.tos);
    setConversationHistory([]);

    const newAnalysisId = doc(collection(db, 'users', user.uid, 'history')).id;
    setAnalysisId(newAnalysisId);

    const result = await analyzeTos(values.tos);
    
    if (result.error) {
      toast({
        variant: 'destructive',
        title: 'Analysis Failed',
        description: result.error,
      });
    } else if (result.data) {
      setAnalysis(result.data);
       try {
        await setDoc(doc(db, 'users', user.uid, 'history', newAnalysisId), {
          tos: values.tos,
          summary: result.data.summary.summary,
          createdAt: serverTimestamp()
        });
       } catch (dbError) {
         console.error("Firestore write error:", dbError);
         toast({
           variant: 'destructive',
           title: 'History Error',
           description: 'Could not save analysis to your history.',
         });
       }
    }
    setIsLoading(false);
  };

  return (
    <div className="flex min-h-screen flex-col bg-background">
      <Header />
      <main className="flex-1 w-full py-8">
        <div className="container mx-auto max-w-4xl px-4">
          <div className="flex justify-between items-center mb-6">
            <h1 className="text-3xl font-bold font-headline">Dashboard</h1>
            <Button variant="ghost" onClick={handleSignOut}>
              Sign Out <LogOut className="ml-2 h-4 w-4" />
            </Button>
          </div>

          <div className="flex flex-col gap-8">
            <Card>
              <CardContent className="p-6">
                <Tabs defaultValue="paste" className="w-full">
                  <TabsList className="grid w-full grid-cols-2">
                    <TabsTrigger value="paste"><FileText className="mr-2"/>Paste Text</TabsTrigger>
                    <TabsTrigger value="upload"><FileUp className="mr-2"/>Upload PDF</TabsTrigger>
                  </TabsList>
                  <form onSubmit={form.handleSubmit(onSubmit)} className="space-y-4 mt-4">
                    <TabsContent value="paste">
                      <h2 className="text-xl font-semibold mb-4">Paste your Terms of Service</h2>
                      <Textarea
                        {...form.register('tos')}
                        placeholder="Paste the entire Terms of Service document here..."
                        className="min-h-[250px] resize-y"
                        disabled={isLoading}
                      />
                    </TabsContent>
                    <TabsContent value="upload">
                       <h2 className="text-xl font-semibold mb-4">Upload a PDF Document</h2>
                       <PdfUploader form={form} disabled={isLoading} />
                    </TabsContent>
                    {form.formState.errors.tos && (
                      <p className="text-sm font-medium text-destructive">
                        {form.formState.errors.tos.message}
                      </p>
                    )}
                    <Button type="submit" disabled={isLoading} className="w-full">
                      {isLoading ? (
                        <>
                          <Loader2 className="mr-2 h-4 w-4 animate-spin" />
                          Analyzing...
                        </>
                      ) : (
                        'Analyze Document'
                      )}
                    </Button>
                  </form>
                </Tabs>
              </CardContent>
            </Card>

            {/* Bottom Section: Analysis Display */}
            <div>
              {isLoading && !analysis && (
                 <div className="flex flex-col items-center justify-center h-full rounded-lg border border-dashed p-8 text-center bg-card min-h-[300px]">
                  <Loader2 className="h-12 w-12 animate-spin text-primary mb-4" />
                  <p className="text-lg font-medium">Analyzing your document...</p>
                  <p className="text-muted-foreground">This may take a moment. Please wait.</p>
                </div>
              )}
              {analysis && user && analysisId && (
                <AnalysisDisplay 
                  analysis={analysis} 
                  tosDocument={tosContent} 
                  userId={user.uid}
                  analysisId={analysisId}
                  conversationHistory={conversationHistory}
                />
              )}
              {!analysis && !isLoading && (
                 <div className="flex flex-col items-center justify-center h-full rounded-lg border border-dashed p-8 text-center bg-card min-h-[300px]">
                  <div className="text-center">
                    <p className="text-lg font-medium">Analysis will appear here</p>
                    <p className="text-muted-foreground">Paste your document or upload a PDF and click "Analyze" to get started.</p>
                  </div>
                </div>
              )}
            </div>
          </div>
        </div>
      </main>
      <Footer />
    </div>
  );
}

function PdfUploader({ form, disabled }: { form: UseFormReturn<z.infer<typeof formSchema>>, disabled: boolean }) {
  const { extractText, text, isLoading, error } = usePdfToText();
  const [fileName, setFileName] = useState('');
  const [isDragOver, setIsDragOver] = useState(false);

  const handleFileChange = async (event: React.ChangeEvent<HTMLInputElement>) => {
    const file = event.target.files?.[0];
    if (file) {
      setFileName(file.name);
      await extractText(file);
    }
  };

  const handleDrop = async (event: React.DragEvent<HTMLLabelElement>) => {
    event.preventDefault();
    event.stopPropagation();
    setIsDragOver(false);
    const file = event.dataTransfer.files?.[0];
    if (file && file.type === 'application/pdf') {
      setFileName(file.name);
      await extractText(file);
    }
  };

  useEffect(() => {
    if (text) {
      form.setValue('tos', text, { shouldValidate: true });
    }
  }, [text, form]);

  return (
     <div className="space-y-4">
      <label
        htmlFor="pdf-upload"
        onDragEnter={() => setIsDragOver(true)}
        onDragLeave={() => setIsDragOver(false)}
        onDragOver={(e) => e.preventDefault()}
        onDrop={handleDrop}
        className={`relative block w-full rounded-lg border-2 border-dashed p-8 text-center cursor-pointer transition-colors ${
          isDragOver ? 'border-primary bg-primary/10' : 'border-border hover:border-primary'
        }`}
      >
        <FileUp className="mx-auto h-12 w-12 text-muted-foreground" />
        <span className="mt-2 block text-sm font-semibold text-foreground">
          Drag & Drop PDF here
        </span>
        <span className="mt-1 block text-xs text-muted-foreground">
          or click to select a file
        </span>
        <Input
          id="pdf-upload"
          type="file"
          accept="application/pdf"
          onChange={handleFileChange}
          disabled={disabled || isLoading}
          className="absolute inset-0 w-full h-full opacity-0 cursor-pointer"
        />
      </label>
      
      {isLoading && (
        <div className="flex items-center space-x-2 text-muted-foreground">
          <Loader2 className="h-4 w-4 animate-spin" />
          <span>Extracting text from {fileName}...</span>
        </div>
      )}
      {error && <p className="text-sm font-medium text-destructive">{error}</p>}
      {text && !isLoading && (
        <p className="text-sm text-green-600">
          Successfully extracted text from {fileName}. You can now analyze the document.
        </p>
      )}
       {!text && !isLoading && !error && (
         <div className="text-sm text-muted-foreground p-4 border border-dashed rounded-md text-center">
            Upload a PDF file to extract its text content.
         </div>
       )}
    </div>
  );
}
