// This is an autogenerated file from Firebase Studio.
'use client';

import { useState } from 'react';
import { useRouter } from 'next/navigation';
import { useForm } from 'react-hook-form';
import { zodResolver } from '@hookform/resolvers/zod';
import { z } from 'zod';
import { onAuthStateChanged, signOut } from 'firebase/auth';
import { auth } from '@/lib/firebase';
import { Button } from '@/components/ui/button';
import { Textarea } from '@/components/ui/textarea';
import { useToast } from '@/hooks/use-toast';
import { analyzeTos, type AnalysisResult } from '@/app/actions';
import { Loader2, LogOut } from 'lucide-react';
import { AnalysisDisplay } from '@/components/app/analysis-display';
import { Header } from '@/components/app/header';
import { Footer } from '@/components/app/footer';

const formSchema = z.object({
  tos: z.string().min(100, {
    message: 'Terms of Service must be at least 100 characters.',
  }),
});

export default function DashboardPage() {
  const [analysis, setAnalysis] = useState<AnalysisResult | null>(null);
  const [isLoading, setIsLoading] = useState(false);
  const [tosContent, setTosContent] = useState('');
  const router = useRouter();
  const { toast } = useToast();

  useState(() => {
    onAuthStateChanged(auth, (user) => {
      if (!user) {
        router.push('/login');
      }
    });
  }, [router]);

  const form = useForm<z.infer<typeof formSchema>>({
    resolver: zodResolver(formSchema),
  });

  const handleSignOut = async () => {
    await signOut(auth);
    router.push('/');
  };

  const onSubmit = async (values: z.infer<typeof formSchema>) => {
    setIsLoading(true);
    setAnalysis(null);
    setTosContent(values.tos);

    const result = await analyzeTos(values.tos);
    
    if (result.error) {
      toast({
        variant: 'destructive',
        title: 'Analysis Failed',
        description: result.error,
      });
    } else if (result.data) {
      setAnalysis(result.data);
    }
    setIsLoading(false);
  };

  return (
    <div className="flex min-h-screen flex-col bg-background">
      <Header />
      <main className="flex-1 w-full py-8">
        <div className="container mx-auto max-w-4xl px-4">
          <div className="flex justify-between items-center mb-6">
            <h1 className="text-3xl font-bold font-headline">Dashboard</h1>
            <Button variant="ghost" onClick={handleSignOut}>
              Sign Out <LogOut className="ml-2 h-4 w-4" />
            </Button>
          </div>

          <div className="flex flex-col gap-8">
            {/* Top Section: ToS Input */}
            <div className="flex flex-col space-y-4">
              <h2 className="text-xl font-semibold">Paste your Terms of Service</h2>
              <form onSubmit={form.handleSubmit(onSubmit)} className="space-y-4">
                <Textarea
                  {...form.register('tos')}
                  placeholder="Paste the entire Terms of Service document here..."
                  className="min-h-[250px] resize-y"
                  disabled={isLoading}
                />
                 {form.formState.errors.tos && (
                  <p className="text-sm font-medium text-destructive">
                    {form.formState.errors.tos.message}
                  </p>
                )}
                <Button type="submit" disabled={isLoading} className="w-full">
                  {isLoading ? (
                    <>
                      <Loader2 className="mr-2 h-4 w-4 animate-spin" />
                      Analyzing...
                    </>
                  ) : (
                    'Analyze Document'
                  )}
                </Button>
              </form>
            </div>

            {/* Bottom Section: Analysis Display */}
            <div>
              {isLoading && !analysis && (
                 <div className="flex flex-col items-center justify-center h-full rounded-lg border border-dashed p-8 text-center bg-card min-h-[300px]">
                  <Loader2 className="h-12 w-12 animate-spin text-primary mb-4" />
                  <p className="text-lg font-medium">Analyzing your document...</p>
                  <p className="text-muted-foreground">This may take a moment. Please wait.</p>
                </div>
              )}
              {analysis && (
                <AnalysisDisplay analysis={analysis} tosDocument={tosContent} />
              )}
              {!analysis && !isLoading && (
                 <div className="flex flex-col items-center justify-center h-full rounded-lg border border-dashed p-8 text-center bg-card min-h-[300px]">
                  <div className="text-center">
                    <p className="text-lg font-medium">Analysis will appear here</p>
                    <p className="text-muted-foreground">Paste your document and click "Analyze" to get started.</p>
                  </div>
                </div>
              )}
            </div>
          </div>
        </div>
      </main>
      <Footer />
    </div>
  );
}
